// Icon registry — the single import surface for UI icons. Components import named
// icons from here (never @mui/icons-material or @icons/* directly). Per-export
// re-exports keep tree-shaking; a tenant swaps an icon in configs/<tenant>/icons.ts
// via 'export * from \'@defaults/icons\'' + an explicit override of that name.
//
// Naming: every icon ends in the `Icon` suffix. Where a MUI icon and an in-house
// icon share a base name, the collision is resolved by adding a usage-context
// prefix (WHERE the icon is used) rather than letting one claim the bare name:
//   Close → CloseIcon (MUI by default; movesmartly maps it to its own thin X)
//   Edit  → ProfileEditIcon (MUI, dashboard profile) | EstimateEditIcon (in-house, estimate cards)
//   Star  → ReviewStarIcon (MUI, review ratings) | StatsStarIcon (in-house, estimate stat banners)
//
// Per-tenant overrides — two mechanisms, pick by WHAT you change:
//   1. Component choice (a different icon component for a slot) → override it in
//      configs/<tenant>/icons.ts ('export * from '@defaults/icons'' + an explicit
//      re-export). This is the PREFERRED, auditable way, and the ONLY option for a
//      slot whose default comes from MUI (the @icons alias can't intercept @mui/...).
//   2. Custom artwork (a tenant's own hand-drawn SVG of an @icons-sourced slot) →
//      drop a same-named file in assets/icons/<tenant>/. No config needed; the
//      @icons/* alias resolves tenant-first.
//   DISCOURAGED: putting a re-export (e.g. of a MUI icon) in assets/icons/<tenant>/.
//   That is a component choice disguised as an asset — it HIDES the swap outside the
//   config. Re-exports belong in the tenant config (1); keep assets/ for real artwork.
//   Precedence: tenant config override > assets/icons/<tenant>/ alias > default.

export { default as AiIcon } from '@icons/AiIcon'
export { default as BathIcon } from '@icons/BathIcon'
export { default as BedIcon } from '@icons/BedIcon'
export { default as CalendarIcon } from '@icons/CalendarIcon'
export { default as CarIcon } from '@icons/CarIcon'
export { default as CircleStarIcon } from '@icons/CircleStarIcon'
export { default as ClipIcon } from '@icons/ClipIcon'
export { default as ClockIcon } from '@icons/ClockIcon'
export { default as CubeIcon } from '@icons/CubeIcon'
export { default as DollarIcon } from '@icons/DollarIcon'
export { default as EmptyFavoritesIcon } from '@icons/EmptyFavoritesIcon'
export { default as EmptyImageFavoritesIcon } from '@icons/EmptyImageFavoritesIcon'
export { default as EmptyListingsIcon } from '@icons/EmptyListingsIcon'
export { default as EstimateEditIcon } from '@icons/EstimateEditIcon'
export { default as FileIcon } from '@icons/FileIcon'
export { default as FilesIcon } from '@icons/FilesIcon'
export { default as GoogleIcon } from '@icons/GoogleIcon'
export { default as HeartEmptyIcon } from '@icons/HeartEmptyIcon'
export { default as HeartIcon } from '@icons/HeartIcon'
export { default as HouseIcon } from '@icons/HouseIcon'
export { default as ImportIcon } from '@icons/ImportIcon'
export { default as KeyIcon } from '@icons/KeyIcon'
export { default as LocationIcon } from '@icons/LocationIcon'
export { default as MapIcon } from '@icons/MapIcon'
export { default as NextIcon } from '@icons/NextIcon'
export { default as PeopleIcon } from '@icons/PeopleIcon'
export { default as PhotoIcon } from '@icons/PhotoIcon'
export { default as PrevIcon } from '@icons/PrevIcon'
export { default as RenovationsIcon } from '@icons/RenovationsIcon'
export { default as RocketIcon } from '@icons/RocketIcon'
export { default as SearchIcon } from '@icons/SearchIcon'
export { default as SettingsIcon } from '@icons/SettingsIcon'
export { default as ShareIcon } from '@icons/ShareIcon'
export { default as SquareIcon } from '@icons/SquareIcon'
export { default as StatsStarIcon } from '@icons/StatsStarIcon'
export { default as UpdateIcon } from '@icons/UpdateIcon'
export { default as UserIcon } from '@icons/UserIcon'
export { default as WorkIcon } from '@icons/WorkIcon'
export { default as AccountBalanceOutlinedIcon } from '@mui/icons-material/AccountBalanceOutlined'
export { default as AddIcon } from '@mui/icons-material/Add'
export { default as ApartmentIcon } from '@mui/icons-material/Apartment'
export { default as ArrowBackIcon } from '@mui/icons-material/ArrowBack'
export { default as ArrowBackIosIcon } from '@mui/icons-material/ArrowBackIos'
export { default as AspectRatioOutlinedIcon } from '@mui/icons-material/AspectRatioOutlined'
export { default as AutoGraphIcon } from '@mui/icons-material/AutoGraph'
export { default as BedtimeTwoToneIcon } from '@mui/icons-material/BedtimeTwoTone'
export { default as BoltIcon } from '@mui/icons-material/Bolt'
export { default as BookmarkBorderIcon } from '@mui/icons-material/BookmarkBorder'
export { default as CheckCircleOutlineIcon } from '@mui/icons-material/CheckCircleOutline'
export { default as ChevronLeftIcon } from '@mui/icons-material/ChevronLeft'
export { default as ChevronRightIcon } from '@mui/icons-material/ChevronRight'
export { default as ClearAllIcon } from '@mui/icons-material/ClearAll'
export { default as CloseIcon } from '@mui/icons-material/Close'
// Reset cross inside a select, drawn in place of the chevron. A slot of its own
// because it has to match whatever MuiSelect.IconComponent draws, not the close
// button of a dialog header: Close and ExpandMore are the same Material set and
// carry the identical 2/24 arm weight, so they swap cleanly at one font size.
export { default as SelectClearIcon } from '@mui/icons-material/Close'
export { default as DeleteOutlineIcon } from '@mui/icons-material/DeleteOutline'
export { default as DeleteOutlinedIcon } from '@mui/icons-material/DeleteOutlined'
export { default as DeleteOutlineOutlinedIcon } from '@mui/icons-material/DeleteOutlineOutlined'
export { default as DescriptionOutlinedIcon } from '@mui/icons-material/DescriptionOutlined'
export { default as DirectionsIcon } from '@mui/icons-material/Directions'
export { default as DirectionsWalkIcon } from '@mui/icons-material/DirectionsWalk'
export { default as DoneOutlinedIcon } from '@mui/icons-material/DoneOutlined'
export { default as DriveEtaOutlinedIcon } from '@mui/icons-material/DriveEtaOutlined'
export { default as ProfileEditIcon } from '@mui/icons-material/Edit'
export { default as EditNotificationsOutlinedIcon } from '@mui/icons-material/EditNotificationsOutlined'
export { default as EditOffOutlinedIcon } from '@mui/icons-material/EditOffOutlined'
export { default as EditOutlinedIcon } from '@mui/icons-material/EditOutlined'
export { default as ErrorOutlineIcon } from '@mui/icons-material/ErrorOutline'
export { default as ExpandLessIcon } from '@mui/icons-material/ExpandLess'
export { default as ExpandMoreIcon } from '@mui/icons-material/ExpandMore'
export { default as ExploreIcon } from '@mui/icons-material/Explore'
export { default as FacebookIcon } from '@mui/icons-material/Facebook'
export { default as FaceRetouchingNaturalIcon } from '@mui/icons-material/FaceRetouchingNatural'
export { default as FenceIcon } from '@mui/icons-material/Fence'
export { default as FolderIcon } from '@mui/icons-material/Folder'
export { default as ForestOutlinedIcon } from '@mui/icons-material/ForestOutlined'
export { default as ForumOutlinedIcon } from '@mui/icons-material/ForumOutlined'
export { default as GestureIcon } from '@mui/icons-material/Gesture'
// Map-style menu trigger — a dedicated slot (defaults to the same Forest glyph)
// so a tenant can swap just this control without touching ForestOutlinedIcon,
// which is also used by MapBackdropIcon.
export { default as MapStyleIcon } from '@mui/icons-material/ForestOutlined'
export { default as GpsFixedIcon } from '@mui/icons-material/GpsFixed'
export { default as HistoryIcon } from '@mui/icons-material/History'
export { default as HistoryOutlinedIcon } from '@mui/icons-material/HistoryOutlined'
export { default as HolidayVillageIcon } from '@mui/icons-material/HolidayVillage'
export { default as HolidayVillageOutlinedIcon } from '@mui/icons-material/HolidayVillageOutlined'
export { default as HomeIcon } from '@mui/icons-material/Home'
export { default as HomeOutlinedIcon } from '@mui/icons-material/HomeOutlined'
export { default as HomeRoundedIcon } from '@mui/icons-material/HomeRounded'
export { default as ImageSearchIcon } from '@mui/icons-material/ImageSearch'
export { default as InfoOutlinedIcon } from '@mui/icons-material/InfoOutlined'
export { default as InsertDriveFileOutlinedIcon } from '@mui/icons-material/InsertDriveFileOutlined'
export { default as InstagramIcon } from '@mui/icons-material/Instagram'
export { default as IosShareOutlinedIcon } from '@mui/icons-material/IosShareOutlined'
export { default as KeyboardArrowDownIcon } from '@mui/icons-material/KeyboardArrowDown'
export { default as KeyboardArrowDownOutlinedIcon } from '@mui/icons-material/KeyboardArrowDownOutlined'
export { default as KeyboardArrowUpOutlinedIcon } from '@mui/icons-material/KeyboardArrowUpOutlined'
export { default as KeyboardDoubleArrowDownOutlinedIcon } from '@mui/icons-material/KeyboardDoubleArrowDownOutlined'
export { default as KeyboardDoubleArrowUpOutlinedIcon } from '@mui/icons-material/KeyboardDoubleArrowUpOutlined'
export { default as LayersOutlinedIcon } from '@mui/icons-material/LayersOutlined'
export { default as LinkedInIcon } from '@mui/icons-material/LinkedIn'
export { default as FeaturesIcon } from '@mui/icons-material/LocalFireDepartmentOutlined'
export { default as LocalShippingOutlinedIcon } from '@mui/icons-material/LocalShippingOutlined'
export { default as MailOutlineIcon } from '@mui/icons-material/MailOutline'
export { default as MapsHomeWorkOutlinedIcon } from '@mui/icons-material/MapsHomeWorkOutlined'
export { default as MeetingRoomIcon } from '@mui/icons-material/MeetingRoom'
export { default as MenuIcon } from '@mui/icons-material/Menu'
export { default as NavigateBeforeIcon } from '@mui/icons-material/NavigateBefore'
export { default as NavigateNextIcon } from '@mui/icons-material/NavigateNext'
export { default as NavigationOutlinedIcon } from '@mui/icons-material/NavigationOutlined'
export { default as OpenInNewIcon } from '@mui/icons-material/OpenInNew'
export { default as PhotoLibraryIcon } from '@mui/icons-material/PhotoLibrary'
export { default as PlaceIcon } from '@mui/icons-material/Place'
export { default as PlaceOutlinedIcon } from '@mui/icons-material/PlaceOutlined'
export { default as PlayArrowIcon } from '@mui/icons-material/PlayArrow'
export { default as PlayArrowRoundedIcon } from '@mui/icons-material/PlayArrowRounded'
// Virtual tour launcher (VirtualTourButton) — named for the slot, not the glyph,
// so a tenant can swap in artwork of a different shape without the name lying.
export { default as VirtualTourIcon } from '@mui/icons-material/PlayCircleOutlined'
export { default as PublicIcon } from '@mui/icons-material/Public'
export { default as RadioButtonCheckedIcon } from '@mui/icons-material/RadioButtonChecked'
export { default as RadioButtonUncheckedIcon } from '@mui/icons-material/RadioButtonUnchecked'
export { default as RefreshIcon } from '@mui/icons-material/Refresh'
export { default as RemoveIcon } from '@mui/icons-material/Remove'
export { default as RestartAltIcon } from '@mui/icons-material/RestartAlt'
export { default as RestartAltOutlinedIcon } from '@mui/icons-material/RestartAltOutlined'
export { default as ReviewsOutlinedIcon } from '@mui/icons-material/ReviewsOutlined'
export { default as SchoolOutlinedIcon } from '@mui/icons-material/SchoolOutlined'
export { default as SchoolRoundedIcon } from '@mui/icons-material/SchoolRounded'
// the listing and building navs' Back to Gallery button
export { default as ScrollToTopIcon } from '@mui/icons-material/BurstModeOutlined'
export { default as SellOutlinedIcon } from '@mui/icons-material/SellOutlined'
export { default as ShieldOutlinedIcon } from '@mui/icons-material/ShieldOutlined'
export { default as SignpostOutlinedIcon } from '@mui/icons-material/SignpostOutlined'
export { default as SmartDisplayOutlinedIcon } from '@mui/icons-material/SmartDisplayOutlined'
export { default as ReviewStarIcon } from '@mui/icons-material/Star'
export { default as StarBorderOutlinedIcon } from '@mui/icons-material/StarBorderOutlined'
export { default as StarOutlinedIcon } from '@mui/icons-material/StarOutlined'
export { default as TaskAltIcon } from '@mui/icons-material/TaskAlt'
export { default as TonalityIcon } from '@mui/icons-material/Tonality'
export { default as TrendingDownIcon } from '@mui/icons-material/TrendingDown'
export { default as TrendingUpIcon } from '@mui/icons-material/TrendingUp'
export { default as VideocamRoundedIcon } from '@mui/icons-material/VideocamRounded'
export { default as ViewDayOutlinedIcon } from '@mui/icons-material/ViewDayOutlined'
export { default as ViewInArIcon } from '@mui/icons-material/ViewInAr'
export { default as ViewModuleRoundedIcon } from '@mui/icons-material/ViewModuleRounded'
export { default as VisibilityOffIcon } from '@mui/icons-material/VisibilityOff'
export { default as VisibilityOffOutlinedIcon } from '@mui/icons-material/VisibilityOffOutlined'
export { default as VrpanoOutlinedIcon } from '@mui/icons-material/VrpanoOutlined'
export { default as WarningAmberOutlinedIcon } from '@mui/icons-material/WarningAmberOutlined'
export { default as WbSunnyTwoToneIcon } from '@mui/icons-material/WbSunnyTwoTone'
export { default as WeekendOutlinedIcon } from '@mui/icons-material/WeekendOutlined'
export { default as WestIcon } from '@mui/icons-material/West'
export { default as WindowOutlinedIcon } from '@mui/icons-material/WindowOutlined'
export { default as XIcon } from '@mui/icons-material/X'
export { default as YouTubeIcon } from '@mui/icons-material/YouTube'

// ListingTypePanel tiles: one slot per selectable listing type (`ListingType` in filters)
export { default as ListingTypeBusinessIcon } from '@mui/icons-material/AccountBalanceOutlined'
export { default as ListingTypeCommercialIcon } from '@mui/icons-material/AccountBalanceOutlined'
export { default as ListingTypeCondoIcon } from '@mui/icons-material/Apartment'
export { default as ListingTypeCoopIcon } from '@mui/icons-material/Apartment'
export { default as ListingTypePenthouseIcon } from '@mui/icons-material/Apartment'
export { default as ListingTypeLoftIcon } from '@mui/icons-material/Apartment'
export { default as ListingTypeLandIcon } from '@mui/icons-material/Fence'
export { default as ListingTypeTownhomeIcon } from '@mui/icons-material/HolidayVillageOutlined'
export { default as ListingTypeSemiDetachedIcon } from '@mui/icons-material/HolidayVillageOutlined'
export { default as ListingTypeResidentialTownhomeIcon } from '@mui/icons-material/HolidayVillageOutlined'
export { default as ListingTypeCondoTownhomeIcon } from '@mui/icons-material/HolidayVillageOutlined'
export { default as ListingTypeResidentialIcon } from '@mui/icons-material/HomeOutlined'
export { default as ListingTypeOtherIcon } from '@mui/icons-material/HomeOutlined'
export { default as ListingTypeAllListingsIcon } from '@mui/icons-material/MapsHomeWorkOutlined'
export { default as ListingTypeMultiFamilyIcon } from '@mui/icons-material/MapsHomeWorkOutlined'
