import type { Rewrite } from 'next/dist/lib/load-custom-routes'

// Default stub — no legacy rewrites for this instance.
// Override in configs/[instance]/rewrites-legacy.ts (auto-generated by generate:legacy-rewrites).

const rewrites: Rewrite[] = []

const redirects: never[] = []

export default { rewrites, redirects }
