/**
 * Pre-build script: generates src/generated/rewrites.json and src/generated/redirects.json
 *
 * Merges these sources (in priority order):
 *   1. rootPage rewrite       — rootPage from configs/[name]/routes.ts (static, since the GrowthBook→config migration)
 *   2. Location-based rewrites — stateCode route alias from locationConfig
 *   3. Instance static rewrites — hardcoded per-instance rules from configs/[name]/rewrites.ts
 *   4. Legacy rewrites        — generated by generate-legacy-rewrites.ts
 *                               stored in configs/[name]/rewrites-legacy.ts
 *   5. Building redirects     — generated by generate-building-redirects.ts
 *                               stored in configs/[name]/redirects-buildings.ts
 *                               only entries with a non-empty destination are included
 *   6. Manual building redirects — hand-authored by managers
 *                               stored in configs/[name]/redirects-buildings-manual.ts
 *                               takes precedence over auto-generated building redirects
 *   7. Location redirects     — generated by generate-location-redirects.ts
 *                               stored in configs/[name]/redirects-locations.ts
 *                               legacy /[neighbourhood]-[city]/* URLs → location pages
 *   8. Documentation rewrites — only while public/documentation exists (build:documentation)
 *
 * Consumed by next.config.js rewrites() / redirects() so that proxy.ts
 * stays lean and only handles true per-request runtime logic.
 *
 * Run via: tsx scripts/generate-rewrites.ts
 */

import fs from 'fs'
import path from 'path'
import dotenv from 'dotenv'
import { fileURLToPath, pathToFileURL } from 'url'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)
const rootDir = path.resolve(dirname, '..')

dotenv.config({ path: path.join(rootDir, '.env'), quiet: true })

const instanceName =
  process.argv[2]?.trim() ||
  String(process.env.NEXT_PUBLIC_APP_CONFIGURATION || '').trim() ||
  'defaults'

const instanceEnvFile = path.join(rootDir, `.env.${instanceName}`)
if (fs.existsSync(instanceEnvFile)) {
  dotenv.config({ path: instanceEnvFile, override: true, quiet: true })
}

// ─── ANSI colours (same convention as fetch-features.ts) ─────────────────────
const c = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  grey: '\x1b[90m',
  red: '\x1b[31m'
}

console.log(`  ENV:\t${instanceName}\n`)

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Try to import a TS module by path; fall back to null on any error. */
async function tryImport<T>(absPath: string): Promise<T | null> {
  try {
    // On Windows, import() requires file:// URLs — bare absolute paths (C:\...) are rejected
    const mod = await import(pathToFileURL(absPath).href)
    return mod.default ?? mod
  } catch {
    return null
  }
}

type RewriteRule = { source: string; destination: string }
type RedirectRule = { source: string; destination: string; permanent: boolean }
type RewritesConfig = { rewrites: RewriteRule[]; redirects: RedirectRule[] }

// ─── 1. rootPage rewrite ─────────────────────────────────────────────────────
// rootPage moved from GrowthBook to static config in the features migration — it now lives
// in configs/[name]/routes.ts (tenant-first, then defaults). Read the scalar straight from
// source (same approach as the location scalars below). Only a non-'landing' value
// ('estimate') produces a / → /<rootPage> rewrite.

function readRootPage(filePath: string): string | undefined {
  try {
    return fs
      .readFileSync(filePath, 'utf-8')
      .match(/rootPage:\s*['"]([^'"]+)['"]/)?.[1]
  } catch {
    return undefined
  }
}

const rootPage =
  readRootPage(path.join(rootDir, `src/configs/${instanceName}/routes.ts`)) ??
  readRootPage(path.join(rootDir, 'src/configs/defaults/routes.ts'))

let rootPageRewrites: RewriteRule[] = []
if (rootPage && rootPage !== 'landing') {
  rootPageRewrites = [{ source: '/', destination: `/${rootPage}` }]
  console.log(`  rootPage rewrite  ${c.green}/ → /${rootPage}${c.reset}`)
} else {
  console.log(
    `  rootPage  ${c.grey}no rewrite (value: ${rootPage ?? 'landing'})${c.reset}`
  )
}

// ─── 2. Location-based rewrites (stateCode route alias) ──────────────────────
//
// location.ts files have deep tsconfig-alias import chains (services/API/types →
// agent, etc.) that Node's dynamic import() cannot resolve at script runtime —
// tryImport() silently returns null.  We read only the two scalar fields we need
// directly from the source text via regex, which is both simpler and reliable.

let locationRewrites: RewriteRule[] = []

function readLocationScalars(filePath: string): {
  stateCode?: string
  useStateCodeRoute?: boolean
} {
  try {
    const src = fs.readFileSync(filePath, 'utf-8')
    const stateCode = src.match(/stateCode:\s*['"]([^'"]+)['"]/)?.[1]
    const useStateCodeRouteRaw = src.match(
      /useStateCodeRoute:\s*(true|false)/
    )?.[1]
    return {
      stateCode,
      useStateCodeRoute:
        useStateCodeRouteRaw === undefined
          ? undefined
          : useStateCodeRouteRaw === 'true'
    }
  } catch {
    return {}
  }
}

// Tenant file overrides defaults; for missing fields fall back to defaults.
// useStateCodeRoute defaults to true when absent from both files (matches defaults config).
const tenantScalars = readLocationScalars(
  path.join(rootDir, `src/configs/${instanceName}/location.ts`)
)
const defaultsScalars = readLocationScalars(
  path.join(rootDir, 'src/configs/defaults/location.ts')
)
const stateCode = tenantScalars.stateCode ?? defaultsScalars.stateCode
const useStateCodeRoute =
  tenantScalars.useStateCodeRoute ?? defaultsScalars.useStateCodeRoute ?? true

if (useStateCodeRoute && stateCode) {
  const code = stateCode.toLowerCase()
  locationRewrites = [
    { source: `/${code}`, destination: '/locations' },
    { source: `/${code}/:path*`, destination: '/locations/:path*' }
  ]
  console.log(
    `  stateCode rewrite  ${c.green}/${code}/* → /locations/*${c.reset}`
  )
} else {
  console.log(`  stateCode  ${c.grey}useStateCodeRoute disabled${c.reset}`)
}

// ─── 3. Instance static rewrites ─────────────────────────────────────────────

let instanceRewrites: RewriteRule[] = []
let instanceRedirects: RedirectRule[] = []

const instanceRewritesPaths = [
  path.join(rootDir, `src/configs/${instanceName}/rewrites.ts`),
  path.join(rootDir, 'src/configs/defaults/rewrites.ts')
]

for (const p of instanceRewritesPaths) {
  if (!fs.existsSync(p)) continue
  const config = await tryImport<RewritesConfig>(p)
  if (config) {
    instanceRewrites = config.rewrites ?? []
    instanceRedirects = config.redirects ?? []
    if (instanceRewrites.length || instanceRedirects.length) {
      console.log(
        `  instance rewrites  ${c.green}${instanceRewrites.length} rewrites, ${instanceRedirects.length} redirects${c.reset}  ${c.grey}(${path.relative(rootDir, p)})${c.reset}`
      )
    }
    break
  }
}

// ─── 4. Legacy rewrites ─────────────────────────────────────────────────────
// Pre-generated by `generate:legacy-rewrites` — maps old WordPress post
// paths to /blog/[path] without requiring a live CMS connection at build time.

let legacyRewrites: RewriteRule[] = []

const legacyRewritesPath = path.join(
  rootDir,
  `src/configs/${instanceName}/rewrites-legacy.ts`
)

const legacyConfig = await tryImport<RewritesConfig>(legacyRewritesPath)
if (legacyConfig) {
  legacyRewrites = legacyConfig.rewrites ?? []
  if (legacyRewrites.length) {
    console.log(
      `  legacy             ${c.green}${legacyRewrites.length} rewrites${c.reset}  ${c.grey}(${path.relative(rootDir, legacyRewritesPath)})${c.reset}`
    )
  }
}

// ─── 5. Building redirects ──────────────────────────────────────────────────
// Pre-generated by `generate:building-redirects` — maps old WordPress building
// URLs to Repliers building pages.
//
// Matched entries (destination non-empty) → redirect to Repliers catalog.
// Unmatched entries (destination: '')     → fallback redirect to /building<source>
//   unless a manual redirect already covers that source (handled in merge).

let buildingRedirects: RedirectRule[] = []
let unmatchedBuildingSources: string[] = []

const buildingRedirectsPath = path.join(
  rootDir,
  `src/configs/${instanceName}/redirects-buildings.ts`
)

const buildingRedirectsRaw = await tryImport<
  { source: string; destination: string; permanent?: boolean }[]
>(buildingRedirectsPath)
if (buildingRedirectsRaw && Array.isArray(buildingRedirectsRaw)) {
  buildingRedirects = buildingRedirectsRaw
    .filter((e) => e.destination)
    .map((e) => ({
      source: e.source,
      destination: e.destination,
      permanent: e.permanent ?? true
    }))
  unmatchedBuildingSources = buildingRedirectsRaw
    .filter((e) => e.source && !e.destination)
    .map((e) => e.source)
  if (buildingRedirects.length) {
    console.log(
      `  buildings          ${c.green}${buildingRedirects.length} redirects${c.reset}  ${c.grey}(${path.relative(rootDir, buildingRedirectsPath)})${c.reset}`
    )
  }
  if (unmatchedBuildingSources.length) {
    console.log(
      `  buildings unmatched  ${c.yellow}${unmatchedBuildingSources.length} will fall back to /building<source>${c.reset}`
    )
  }
}

// ─── 6. Manual building redirects ──────────────────────────────────────────────
// Hand-authored by managers in configs/[name]/redirects-buildings-manual.ts.
// Covers buildings that were not auto-matched (destination was empty in
// redirects-buildings.ts). Takes precedence over auto-generated entries.

let buildingManualRedirects: RedirectRule[] = []

const buildingManualPaths = [
  path.join(
    rootDir,
    `src/configs/${instanceName}/redirects-buildings-manual.ts`
  ),
  path.join(rootDir, 'src/configs/defaults/redirects-buildings-manual.ts')
]

for (const p of buildingManualPaths) {
  if (!fs.existsSync(p)) continue
  const raw =
    await tryImport<
      { source: string; destination: string; permanent?: boolean }[]
    >(p)
  if (raw && Array.isArray(raw)) {
    buildingManualRedirects = raw.map((e) => ({
      source: e.source,
      destination: e.destination,
      permanent: e.permanent ?? true
    }))
    if (buildingManualRedirects.length) {
      console.log(
        `  buildings manual   ${c.green}${buildingManualRedirects.length} redirects${c.reset}  ${c.grey}(${path.relative(rootDir, p)})${c.reset}`
      )
    }
    break
  }
}

// ─── 7. Location redirects ──────────────────────────────────────────────────
// Pre-generated by `generate:location-redirects` — maps the legacy
// /[neighbourhood]-[city]/[anything] URLs onto the portal's location pages.
// Always permanent, so the flag is stamped here instead of in ~900 rows.

let locationRedirects: RedirectRule[] = []

const locationRedirectsPath = path.join(
  rootDir,
  `src/configs/${instanceName}/redirects-locations.ts`
)

const locationRedirectsRaw = await tryImport<RewriteRule[]>(
  locationRedirectsPath
)
if (Array.isArray(locationRedirectsRaw)) {
  locationRedirects = locationRedirectsRaw.map((r) => ({
    ...r,
    permanent: true
  }))
  console.log(
    `  locations          ${c.green}${locationRedirects.length} redirects${c.reset}  ${c.grey}(${path.relative(rootDir, locationRedirectsPath)})${c.reset}`
  )
}

// ─── 8. Documentation rewrites ──────────────────────────────────────────────
// Static Nextra exports assembled by `build:documentation`; their pages are
// `<page>/index.html`. These run as beforeFiles — ahead of public/ — so the
// dotless pattern leaves assets, index.html and RSC .txt payloads to the
// public file itself. The proxy route guard allowlists the /documentation
// prefix from this source, so tenants without the folder keep today's guard.

const documentationRewrites: RewriteRule[] = fs.existsSync(
  path.join(rootDir, 'public', 'documentation')
)
  ? [
      { source: '/documentation', destination: '/documentation/index.html' },
      {
        source: '/documentation/:path([^.]+)',
        destination: '/documentation/:path/index.html'
      }
    ]
  : []
if (documentationRewrites.length) {
  console.log(
    `  documentation      ${c.green}${documentationRewrites.length} rewrites${c.reset}  ${c.grey}(public/documentation)${c.reset}`
  )
}

// ─── Merge & write ────────────────────────────────────────────────────────────

const allRewrites: RewriteRule[] = [
  ...rootPageRewrites, // highest priority — rootPage override
  ...locationRewrites, // state code alias
  ...instanceRewrites, // instance-level static aliases
  ...legacyRewrites, // WP legacy paths → /blog/...
  ...documentationRewrites // own /documentation prefix, collides with none above
]

// Manual entries override auto-generated ones for the same source path.
// Dedup: build a Map keyed by source so manual wins on collision.
const buildingRedirectsMap = new Map<string, RedirectRule>()
for (const r of [...buildingRedirects, ...buildingManualRedirects]) {
  buildingRedirectsMap.set(r.source, r)
}

// Fallback: for unmatched WP building sources not covered by a manual redirect,
// add a redirect to /building<source> (the WP-only CMS building route).
const manualSources = new Set(buildingManualRedirects.map((r) => r.source))
let fallbackCount = 0
for (const source of unmatchedBuildingSources) {
  if (!manualSources.has(source)) {
    buildingRedirectsMap.set(source, {
      source,
      destination: `/building${source}`,
      permanent: false
    })
    fallbackCount++
  }
}
if (fallbackCount > 0) {
  console.log(
    `  buildings fallback ${c.green}${fallbackCount} → /building<source>${c.reset}`
  )
}

const allBuildingRedirects = [...buildingRedirectsMap.values()]

// Location rules match on a bare first segment, so they go last — every literal
// rule above gets to claim its path first.
const allRedirects: RedirectRule[] = [
  ...instanceRedirects,
  ...allBuildingRedirects,
  ...locationRedirects
]

fs.writeFileSync(
  path.join(rootDir, 'rewrites.generated.json'),
  JSON.stringify(allRewrites, null, 2)
)
fs.writeFileSync(
  path.join(rootDir, 'redirects.generated.json'),
  JSON.stringify(allRedirects, null, 2)
)

console.log(
  `\n  ${c.green}✓${c.reset} wrote rewrites.generated.json   (${allRewrites.length} rules)`
)
console.log(
  `  ${c.green}✓${c.reset} wrote redirects.generated.json  (${allRedirects.length} rules)\n`
)
