/**
 * Pre-build script: turns the cached locations tree into redirects from the
 * legacy `/<neighbourhood>-<city>/<anything>` URLs onto the portal's location
 * pages. See location-redirects-core.ts for the URL shapes and why two rules per
 * neighbourhood are needed.
 *
 * Input:  public/[instance]/locations.json   (pnpm generate:locations [instance])
 * Output: src/configs/[instance]/redirects-locations.ts
 *
 * The output is picked up by generate-rewrites.ts as source #7 during the
 * pre-build step, which stamps every rule `permanent: true`. Commit the file —
 * it is regenerated only when the locations tree is.
 *
 * Usage:
 *   tsx scripts/generate-location-redirects.ts                  # NEXT_PUBLIC_APP_CONFIGURATION from .env
 *   tsx scripts/generate-location-redirects.ts movesmartly-com  # explicit instance
 */

import fs from 'fs'
import path from 'path'
import dotenv from 'dotenv'
import { fileURLToPath } from 'url'

import { buildLocationRedirects } from './location-redirects-core'

const filename = fileURLToPath(import.meta.url)
const rootDir = path.resolve(path.dirname(filename), '..')

dotenv.config({ path: path.join(rootDir, '.env'), quiet: true })

const instanceName =
  process.argv[2]?.trim() ||
  String(process.env.NEXT_PUBLIC_APP_CONFIGURATION || '').trim() ||
  'defaults'

const instanceEnvFile = path.join(rootDir, `.env.${instanceName}`)
if (fs.existsSync(instanceEnvFile)) {
  dotenv.config({ path: instanceEnvFile, override: true, quiet: true })
}

const c = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  grey: '\x1b[90m',
  red: '\x1b[31m'
}

console.log(
  `\n  generate-location-redirects  ${c.grey}instance:${c.reset} ${instanceName}\n`
)

// ─── Destination prefix ──────────────────────────────────────────────────────
// Same two scalars getLocationUrl() builds its prefix from, read the same way
// generate-rewrites.ts reads them: location.ts has deep alias import chains that
// Node's dynamic import() cannot resolve at script runtime.

function readLocationScalars(filePath: string): {
  stateCode?: string
  useStateCodeRoute?: boolean
} {
  try {
    const src = fs.readFileSync(filePath, 'utf-8')
    const raw = src.match(/useStateCodeRoute:\s*(true|false)/)?.[1]
    return {
      stateCode: src.match(/stateCode:\s*['"]([^'"]+)['"]/)?.[1],
      useStateCodeRoute: raw === undefined ? undefined : raw === 'true'
    }
  } catch {
    return {}
  }
}

const tenantScalars = readLocationScalars(
  path.join(rootDir, `src/configs/${instanceName}/location.ts`)
)
const defaultsScalars = readLocationScalars(
  path.join(rootDir, 'src/configs/defaults/location.ts')
)
const stateCode = tenantScalars.stateCode ?? defaultsScalars.stateCode
const useStateCodeRoute =
  tenantScalars.useStateCodeRoute ?? defaultsScalars.useStateCodeRoute ?? true

const prefix =
  useStateCodeRoute && stateCode ? `/${stateCode.toLowerCase()}` : '/locations'

// ─── Tree ────────────────────────────────────────────────────────────────────

const treePath = path.join(rootDir, `public/${instanceName}/locations.json`)

if (!fs.existsSync(treePath)) {
  console.error(
    `  ${c.red}error:${c.reset} ${path.relative(rootDir, treePath)} not found\n` +
      `         Run "pnpm generate:locations ${instanceName}" first\n`
  )
  process.exit(1)
}

const { tree } = JSON.parse(fs.readFileSync(treePath, 'utf-8'))
const redirects = buildLocationRedirects(tree.areas ?? [], prefix)

console.log(`  prefix     ${c.green}${prefix}/<city>/<neighbourhood>${c.reset}`)
console.log(
  `  tree       ${c.grey}${path.relative(rootDir, treePath)}${c.reset}\n`
)

// ─── Write ───────────────────────────────────────────────────────────────────

const outputPath = path.join(
  rootDir,
  `src/configs/${instanceName}/redirects-locations.ts`
)

// An apostrophe survives encodeURIComponent, so a few destinations carry one
// (/on/scarborough/tam-o'shanter-sullivan). Switching quote style for those is
// what prettier would do anyway, and it keeps every value escape-free.
const quote = (value: string) =>
  value.includes("'") ? JSON.stringify(value) : `'${value}'`

// Emit what prettier would print, so a fresh generate is already commit-clean:
// one field per line, wrapped after the colon once the line passes 80 columns.
const field = (name: string, value: string, comma = '') => {
  const line = `    ${name}: ${quote(value)}${comma}`
  return line.length <= 80
    ? line
    : `    ${name}:\n      ${quote(value)}${comma}`
}

fs.writeFileSync(
  outputPath,
  [
    `// Auto-generated by scripts/generate-location-redirects.ts`,
    `// Run: pnpm generate:location-redirects ${instanceName}`,
    `// Do not edit manually.`,
    ``,
    `const redirects: { source: string; destination: string }[] = [`,
    redirects
      .map(({ source, destination }) =>
        [
          `  {`,
          field('source', source, ','),
          field('destination', destination),
          `  }`
        ].join('\n')
      )
      .join(',\n'),
    `]`,
    ``,
    `export default redirects`,
    ``
  ].join('\n')
)

console.log(
  `  ${c.green}✓${c.reset} wrote ${path.relative(rootDir, outputPath)}  (${redirects.length} redirects)\n`
)
